name: Run tests
on:
  workflow_call

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Settle pip/pip-tools versions
        run: |
          python -m pip install --upgrade "pip<25.3"
          python -m pip install --upgrade "pip-tools"
      - name: Install compile dependencies
        run: pip-compile --output-file=requirements.txt requirements-base.in requirements-dev.in requirements.in
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Run unit tests
        run: pytest
